set_property IOSTANDARD LVCMOS33 [get_ports {edit_index[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {edit_index[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mode[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mode[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mode[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mode[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mode[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mode[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mode[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mode[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segments[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segments[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segments[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segments[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segments[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segments[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segments[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segments[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segments[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segments[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segments[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segments[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segments[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segments[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segments[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segments[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports btn1]
set_property IOSTANDARD LVCMOS33 [get_ports btn2]
set_property IOSTANDARD LVCMOS33 [get_ports btn3]
set_property IOSTANDARD LVCMOS33 [get_ports btn4]
set_property IOSTANDARD LVCMOS33 [get_ports btn5]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports light]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports segment1_control]
set_property IOSTANDARD LVCMOS33 [get_ports segment2_control]
set_property IOSTANDARD LVCMOS33 [get_ports segment3_control]
set_property IOSTANDARD LVCMOS33 [get_ports segment4_control]
set_property IOSTANDARD LVCMOS33 [get_ports segment5_control]
set_property IOSTANDARD LVCMOS33 [get_ports segment6_control]
set_property IOSTANDARD LVCMOS33 [get_ports sw]
set_property IOSTANDARD LVCMOS33 [get_ports sw_light]
set_property PACKAGE_PIN K1 [get_ports {edit_index[1]}]
set_property PACKAGE_PIN H6 [get_ports {edit_index[0]}]
set_property PACKAGE_PIN F6 [get_ports {mode[7]}]
set_property PACKAGE_PIN G4 [get_ports {mode[6]}]
set_property PACKAGE_PIN G3 [get_ports {mode[5]}]
set_property PACKAGE_PIN J4 [get_ports {mode[4]}]
set_property PACKAGE_PIN H4 [get_ports {mode[3]}]
set_property PACKAGE_PIN J3 [get_ports {mode[2]}]
set_property PACKAGE_PIN J2 [get_ports {mode[1]}]
set_property PACKAGE_PIN K2 [get_ports {mode[0]}]
set_property PACKAGE_PIN B4 [get_ports {segments[15]}]
set_property PACKAGE_PIN A4 [get_ports {segments[14]}]
set_property PACKAGE_PIN A3 [get_ports {segments[13]}]
set_property PACKAGE_PIN B1 [get_ports {segments[12]}]
set_property PACKAGE_PIN A1 [get_ports {segments[11]}]
set_property PACKAGE_PIN B3 [get_ports {segments[10]}]
set_property PACKAGE_PIN B2 [get_ports {segments[9]}]
set_property PACKAGE_PIN D5 [get_ports {segments[8]}]
set_property PACKAGE_PIN D4 [get_ports {segments[7]}]
set_property PACKAGE_PIN E3 [get_ports {segments[6]}]
set_property PACKAGE_PIN D3 [get_ports {segments[5]}]
set_property PACKAGE_PIN F4 [get_ports {segments[4]}]
set_property PACKAGE_PIN F3 [get_ports {segments[3]}]
set_property PACKAGE_PIN E2 [get_ports {segments[2]}]
set_property PACKAGE_PIN D2 [get_ports {segments[1]}]
set_property PACKAGE_PIN H2 [get_ports {segments[0]}]
set_property PACKAGE_PIN V1 [get_ports btn1]
set_property PACKAGE_PIN U4 [get_ports btn2]
set_property PACKAGE_PIN R15 [get_ports btn3]
set_property PACKAGE_PIN R17 [get_ports btn4]
set_property PACKAGE_PIN R11 [get_ports btn5]
set_property PACKAGE_PIN P17 [get_ports clk]
set_property PACKAGE_PIN K3 [get_ports light]
set_property PACKAGE_PIN P5 [get_ports rst]
set_property PACKAGE_PIN C1 [get_ports segment1_control]
set_property PACKAGE_PIN H1 [get_ports segment2_control]
set_property PACKAGE_PIN G1 [get_ports segment3_control]
set_property PACKAGE_PIN F1 [get_ports segment4_control]
set_property PACKAGE_PIN E1 [get_ports segment5_control]
set_property PACKAGE_PIN G6 [get_ports segment6_control]
set_property PACKAGE_PIN R1 [get_ports sw]
set_property PACKAGE_PIN T5 [get_ports sw_light]



set_property IOSTANDARD LVCMOS33 [get_ports {setting_page_index[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {setting_page_index[0]}]
set_property PACKAGE_PIN H5 [get_ports {setting_page_index[1]}]
set_property PACKAGE_PIN J5 [get_ports {setting_page_index[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports beelight]
set_property PACKAGE_PIN M1 [get_ports beelight]

set_property IOSTANDARD LVCMOS33 [get_ports {edit_index_light[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {edit_index_light[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {setting_page_index_light[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {setting_page_index_light[0]}]
set_property PACKAGE_PIN H5 [get_ports {edit_index_light[1]}]
set_property PACKAGE_PIN J5 [get_ports {edit_index_light[0]}]
set_property PACKAGE_PIN K1 [get_ports {setting_page_index_light[1]}]
set_property PACKAGE_PIN H6 [get_ports {setting_page_index_light[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports audio_sd]
set_property PACKAGE_PIN M6 [get_ports audio_sd]
set_property IOSTANDARD LVCMOS33 [get_ports audio_pwm]
set_property PACKAGE_PIN T1 [get_ports audio_pwm]

set_property IOSTANDARD LVCMOS33 [get_ports query_page_index_light]
set_property PACKAGE_PIN K6 [get_ports query_page_index_light]

set_property PACKAGE_PIN N4 [get_ports lb_sel_pin]
set_property IOSTANDARD LVCMOS33 [get_ports lb_sel_pin]


set_property PACKAGE_PIN L3 [get_ports rxd_pin]
set_property IOSTANDARD LVCMOS33 [get_ports rxd_pin]
set_property PACKAGE_PIN N2 [get_ports txd_pin]
set_property IOSTANDARD LVCMOS33 [get_ports txd_pin]
set_property -dict {PACKAGE_PIN P4 IOSTANDARD LVCMOS33} [get_ports {sw_pin[0]}]
set_property -dict {PACKAGE_PIN P3 IOSTANDARD LVCMOS33} [get_ports {sw_pin[1]}]
set_property -dict {PACKAGE_PIN P2 IOSTANDARD LVCMOS33} [get_ports {sw_pin[2]}]
set_property -dict {PACKAGE_PIN R2 IOSTANDARD LVCMOS33} [get_ports {sw_pin[3]}]
set_property -dict {PACKAGE_PIN M4 IOSTANDARD LVCMOS33} [get_ports {sw_pin[4]}]


set_property -dict {PACKAGE_PIN D18 IOSTANDARD LVCMOS33} [get_ports bt_pw_on]
set_property -dict {PACKAGE_PIN C16 IOSTANDARD LVCMOS33} [get_ports bt_master_slave]
set_property -dict {PACKAGE_PIN H15 IOSTANDARD LVCMOS33} [get_ports bt_sw_hw]
set_property -dict {PACKAGE_PIN M2 IOSTANDARD LVCMOS33} [get_ports bt_rst_n]
set_property -dict {PACKAGE_PIN E18 IOSTANDARD LVCMOS33} [get_ports bt_sw]


set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property PACKAGE_PIN U3 [get_ports rst_n]
